version: 2.1
description: A greeting command orb
commands:
 greet:
     steps:
        - run:
            name: updating
            command: |
              echo 'export TESTING="OOGAHBOOGAH"' >> $BASH_ENV
        - run: echo $TESTING
         
